### ISSUE TITLE
AspNet Middleware Configuration: IgnoredRoutesRegexPatterns vs IgnoredRequestPatterns

### ISSUE THREAD

**Issue by JasonSoares** [alhardy/AppMetrics.DocFx#7]
First off, this library is some fantastic work!

When comparing the documentation for the following files, I noticed that the json file uses the `IgnoredRequestPatterns` key while the `configuration.md` file lists the `IgnoredRoutesRegexPatterns` key.

* `/src/samples/App.Metrics.Formatters.Json.Samples/AspNetOptions.json`
* `web-applictaion-monitoring/configuration.md`

I believe the key in the json file should be changed to `IgnoredRoutesRegexPatterns`.  I tested this  in an app that I'm working on, and `IgnoredRequestPatterns` does not work, but `IgnoredRoutesRegexPatterns` does.

**Comment by alhardy** [comment]
@JasonSoares thank you for feedback and for pointing out a couple of issues in the documentation, really helps 👍
