### ISSUE TITLE
Health Checks and nuget packages to include

### ISSUE THREAD

**Issue by JasonSoares** [alhardy/AppMetrics.DocFx#8]
I wanted to share an issue that tripped me up a bit, since it may be an opportunity to help some future new user.

I started my own sample project to explore this library, and in the beginning I followed the `Getting Started` > `Configuring a Web Host` instructions, adding the `App.Metrics.Extensions.Middleware` and `App.Metrics.Formatters.Json` nuget packages.

Later, I tried to create a health check class, which inherited `HealthCheck`, but it did not work.  What ended up making it work, was adding the `App.Metrics` nuget package.

I would suggest mentioning adding this package either in the intro, or on the `Health Checks` page (or both).

**Comment by alhardy** [comment]
Thanks for point that out @JasonSoares. I've updated the docs for now, However this shouldn't be required, logged an issue for that https://github.com/alhardy/AppMetrics/issues/136
